# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0006_version_1_8_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='core_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_core', to='NEMO.Core'),
        ),
        migrations.AddField(
            model_name='tool',
            name='core_id',
            field=models.ForeignKey(help_text='The core facility of which this tool is part.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_core', to='NEMO.Core'),
        ),
        migrations.AddField(
            model_name='user',
            name='core_ids',
            field=models.ManyToManyField(blank=True, related_name='user_core', to='NEMO.Core'),
        ),
    ]
