# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0007_auto_20190501_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablewithdraw',
            name='core_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conswith_core', to='NEMO.Core'),
        ),
    ]
