# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0008_consumablewithdraw_core_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='reservation_required',
            field=models.BooleanField(default=False, help_text='Require that users have a current (within 15 minutes) reservation in order to use the tool'),
        ),
    ]
