# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0009_tool_reservation_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumablewithdraw',
            name='core_id',
        ),
        migrations.AddField(
            model_name='consumable',
            name='core_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumable_core', to='NEMO.Core'),
        ),
        migrations.AlterField(
            model_name='landingpagechoice',
            name='secure_referral',
            field=models.BooleanField(default=True, help_text="Improves security by blocking HTTP referer [sic] information from the targeted page. Enabling this prevents the target page from manipulating the calling page's DOM with JavaScript. This should always be used for external links. It is safe to uncheck this when linking within the LEO site. Leave this box checked if you don't know what this means"),
        ),
        migrations.AlterField(
            model_name='landingpagechoice',
            name='url',
            field=models.CharField(help_text='The URL that the choice leads to when clicked. Relative paths such as /calendar/ are used when linking within the LEO site. Use fully qualified URL paths such as https://www.google.com/ to link to external sites.', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user can log in to LEO. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
