# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 14:08
from __future__ import unicode_literals

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0010_auto_20190521_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(null=True),
        ),
    ]
