# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-30 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0010_auto_20190521_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalaccesslog',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NEMO.Area'),
        ),
        migrations.AlterField(
            model_name='physicalaccesslog',
            name='door',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NEMO.Door'),
        ),
    ]
