# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-26 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0011_auto_20190730_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAccessRecordProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffChargeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEMO.Project')),
            ],
        ),
        migrations.CreateModel(
            name='UsageEventProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEMO.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='areaaccessrecord',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='areaaccessrecord',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_access_record_project', to='NEMO.Project'),
        ),
        migrations.AlterField(
            model_name='staffcharge',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_charge_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffcharge',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_charge_project', to='NEMO.Project'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_event_project', to='NEMO.Project'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_event_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usageeventproject',
            name='usage_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEMO.UsageEvent'),
        ),
        migrations.AddField(
            model_name='staffchargeproject',
            name='staff_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEMO.StaffCharge'),
        ),
        migrations.AddField(
            model_name='areaaccessrecordproject',
            name='area_access_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEMO.AreaAccessRecord'),
        ),
        migrations.AddField(
            model_name='areaaccessrecordproject',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='areaaccessrecordproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEMO.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='accesses',
            field=models.ManyToManyField(related_name='project_accesses', through='NEMO.AreaAccessRecordProject', to='NEMO.AreaAccessRecord'),
        ),
        migrations.AddField(
            model_name='project',
            name='events',
            field=models.ManyToManyField(related_name='project_events', through='NEMO.UsageEventProject', to='NEMO.UsageEvent'),
        ),
        migrations.AddField(
            model_name='project',
            name='staff_charges',
            field=models.ManyToManyField(related_name='project_staff_charges', through='NEMO.StaffChargeProject', to='NEMO.StaffCharge'),
        ),
    ]
