# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-27 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0013_auto_20190827_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaaccessrecordproject',
            name='project_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='staffchargeproject',
            name='project_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='usageeventproject',
            name='project_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
