# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-13 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0015_auto_20190911_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaaccessrecordproject',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='areaaccessrecordproject',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='staffcharge',
            name='charge_end_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffcharge',
            name='override_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffcharge',
            name='related_override_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NEMO.StaffCharge'),
        ),
        migrations.AddField(
            model_name='staffchargeproject',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='staffchargeproject',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='usageeventproject',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='usageeventproject',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
