# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-02 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0016_auto_20190913_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaaccessrecord',
            name='customers',
            field=models.ManyToManyField(related_name='AreaAccessRecordMultipleCustomers', through='NEMO.AreaAccessRecordProject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffcharge',
            name='customers',
            field=models.ManyToManyField(through='NEMO.StaffChargeProject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='customers',
            field=models.ManyToManyField(through='NEMO.UsageEventProject', to=settings.AUTH_USER_MODEL),
        ),
    ]
