# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0017_auto_20191002_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcharge',
            name='ad_hoc_related',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='staffcharge',
            name='ad_hoc_replaced',
            field=models.BooleanField(default=False),
        ),
    ]
