# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-17 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0018_auto_20191003_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='consumable',
            field=models.ManyToManyField(blank=True, help_text='Select the core-specific consumables that are configurable choices for the selected tool.', to='NEMO.Consumable'),
        ),
    ]
