# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-17 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0019_configuration_consumable'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcharge',
            name='contest_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffcharge',
            name='contested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='contest_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='contested',
            field=models.BooleanField(default=False),
        ),
    ]
