# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-24 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0021_auto_20191023_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablewithdraw',
            name='project_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
