# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-25 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0023_reservationconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationconfiguration',
            name='setting',
            field=models.TextField(blank=True, null=True),
        ),
    ]
