# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-29 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0024_reservationconfiguration_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='exclude_from_configuration_agenda',
            field=models.BooleanField(default=False, help_text="Reservations containing this configuration will be excluded from the laboratory technician's Configuration Agenda page."),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='self_configuration',
            field=models.BooleanField(default=False, help_text='When checked, indicates that the user will perform their own tool configuration (instead of requesting that the laboratory staff configure it for them).'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='short_notice',
            field=models.BooleanField(default=None, help_text='Indicates that the reservation was made after the configuration deadline for a tool. Laboratory staff may not have enough time to properly configure the tool before the user is scheduled to use it.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='safety_hazard',
            field=models.BooleanField(default=None, help_text='Indicates that this task represents a safety hazard to the laboratory.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='badge_number',
            field=models.PositiveIntegerField(blank=True, help_text='The badge number associated with this user. This number must correctly correspond to a user in order for the tablet-login system (in the lobby) to work properly.', null=True, unique=True),
        ),
    ]
