# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-14 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0028_auto_20191107_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaaccessrecord',
            name='no_charge_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumablewithdraw',
            name='no_charge_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumablewithdraw',
            name='usage_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumable_usage_event', to='NEMO.UsageEvent'),
        ),
        migrations.AddField(
            model_name='staffcharge',
            name='no_charge_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='no_charge_flag',
            field=models.BooleanField(default=False),
        ),
    ]
