# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-15 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('NEMO', '0029_auto_20191114_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=50)),
                ('original_value', models.CharField(max_length=250)),
                ('proposed_value', models.CharField(max_length=250)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['content_type', '-object_id'],
            },
        ),
    ]
