# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-26 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0030_contesttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaaccessrecord',
            name='contest_resolution_desciption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumablewithdraw',
            name='contest_resolution_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffcharge',
            name='contest_resolution_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='contest_resolution_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
