# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-02 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('NEMO', '0031_auto_20191126_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestTransactionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=50)),
                ('original_value', models.CharField(max_length=250)),
                ('proposed_value', models.CharField(max_length=250)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['content_type', '-object_id'],
            },
        ),
        migrations.RemoveField(
            model_name='areaaccessrecord',
            name='contest_description',
        ),
        migrations.RemoveField(
            model_name='areaaccessrecord',
            name='contest_resolution_desciption',
        ),
        migrations.RemoveField(
            model_name='areaaccessrecord',
            name='contest_resolved',
        ),
        migrations.RemoveField(
            model_name='areaaccessrecord',
            name='contest_resolved_date',
        ),
        migrations.RemoveField(
            model_name='areaaccessrecord',
            name='contested_date',
        ),
        migrations.RemoveField(
            model_name='consumablewithdraw',
            name='contest_description',
        ),
        migrations.RemoveField(
            model_name='consumablewithdraw',
            name='contest_resolution_description',
        ),
        migrations.RemoveField(
            model_name='consumablewithdraw',
            name='contest_resolved',
        ),
        migrations.RemoveField(
            model_name='consumablewithdraw',
            name='contest_resolved_date',
        ),
        migrations.RemoveField(
            model_name='consumablewithdraw',
            name='contested_date',
        ),
        migrations.RemoveField(
            model_name='contesttransaction',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='contesttransaction',
            name='original_value',
        ),
        migrations.RemoveField(
            model_name='contesttransaction',
            name='proposed_value',
        ),
        migrations.RemoveField(
            model_name='staffcharge',
            name='contest_description',
        ),
        migrations.RemoveField(
            model_name='staffcharge',
            name='contest_resolution_description',
        ),
        migrations.RemoveField(
            model_name='staffcharge',
            name='contest_resolved',
        ),
        migrations.RemoveField(
            model_name='staffcharge',
            name='contest_resolved_date',
        ),
        migrations.RemoveField(
            model_name='staffcharge',
            name='contested_date',
        ),
        migrations.RemoveField(
            model_name='usageevent',
            name='contest_description',
        ),
        migrations.RemoveField(
            model_name='usageevent',
            name='contest_resolution_description',
        ),
        migrations.RemoveField(
            model_name='usageevent',
            name='contest_resolved',
        ),
        migrations.RemoveField(
            model_name='usageevent',
            name='contest_resolved_date',
        ),
        migrations.RemoveField(
            model_name='usageevent',
            name='contested_date',
        ),
        migrations.AddField(
            model_name='contesttransaction',
            name='contest_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contesttransaction',
            name='contest_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contesttransaction',
            name='contest_resolution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contesttransaction',
            name='contest_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contesttransaction',
            name='contest_resolved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contesttransaction',
            name='contested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contesttransactiondata',
            name='contest_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEMO.ContestTransaction'),
        ),
    ]
