# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-13 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0032_auto_20191202_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(help_text='indicator for the fiscal year in the format 20192020', max_length=20)),
                ('billing_month', models.PositiveIntegerField(help_text='integer indicating the month: 1 = January, 12 = December')),
                ('billing_year', models.PositiveIntegerField(help_text='the current year for which the month is being locked')),
                ('is_locked', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
