# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-03 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0034_auto_20200320_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cost_center',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='end_date',
            field=models.DateField(blank=True, help_text='The date on which the cost center becomes inactive', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The owner or person responsible for the Account (Cost Center in SIMBA) as imported via SIMBA download nightly', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='start_date',
            field=models.DateField(blank=True, help_text='The date on which the cost center becomes active', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='The date on which the project, internal order or wbs element becomes inactive', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='internal_order',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The owner or person responsible for the Project (Internal Order or WBS Element in SIMBA) as imported via SIMBA download nightly', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='The date on which the project, internal order or wbs element becomes active', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='wbs_element',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
