# Generated by Django 2.2.12 on 2020-04-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0036_auto_20200420_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fa_type_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rate_type_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
