# Generated by Django 2.2.12 on 2020-05-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0038_reservationproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcharge',
            name='staff_member_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='operator_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
