# Generated by Django 2.2.12 on 2020-05-20 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0040_globalflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customers',
            field=models.ManyToManyField(related_name='reservation_customers', through='NEMO.ReservationProject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='projects',
            field=models.ManyToManyField(related_name='reservation_projects', through='NEMO.ReservationProject', to='NEMO.Project'),
        ),
    ]
