# Generated by Django 2.2.12 on 2020-05-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0041_auto_20200520_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='cost_center',
            new_name='simba_cost_center',
        ),
        migrations.AddField(
            model_name='account',
            name='ibis_account',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.CharField(blank=True, max_length=20, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
