# Generated by Django 2.2.12 on 2020-05-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0042_auto_20200527_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='simba_cost_center',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
