# Generated by Django 2.2.12 on 2020-06-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0045_auto_20200610_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaaccessrecord',
            name='ad_hoc_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffcharge',
            name='ad_hoc_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='ad_hoc_created',
            field=models.BooleanField(default=False),
        ),
    ]
