# Generated by Django 2.2.12 on 2020-06-15 16:59

import NEMO.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0049_fico_coa_fico_coa_person_responsible_fico_gl_acct'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffchargeproject',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usageeventproject',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(blank=True, default=NEMO.models.get_new_project_number, max_length=20, null=True),
        ),
    ]
