# Generated by Django 2.2.12 on 2020-06-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0050_auto_20200615_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablewithdraw',
            name='project_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
