# Generated by Django 2.2.12 on 2020-06-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0051_auto_20200618_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='application_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CreditCostCollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('core', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.Core')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.Project')),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='credit_cost_collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_credit_account', to='NEMO.CreditCostCollector'),
        ),
        migrations.AddField(
            model_name='user',
            name='credit_cost_collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_credit_account', to='NEMO.CreditCostCollector'),
        ),
    ]
