# Generated by Django 2.2.12 on 2020-06-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0052_auto_20200621_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='credit_cost_collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_cost_collector', to='NEMO.CreditCostCollector'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='credit_cost_collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_cost_collector', to='NEMO.CreditCostCollector'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='core_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_core', to='NEMO.Core'),
        ),
    ]
