# Generated by Django 2.2.12 on 2020-06-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0053_auto_20200622_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ibis_account',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='simba_cost_center',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
