# Generated by Django 2.2.12 on 2020-06-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0055_auto_20200624_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='image',
            field=models.ImageField(blank=True, help_text='Portraits are resized to 266 pixels high and 200 pixels wide. Crop portraits to these dimensions before uploading for optimal bandwidth usage', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='office_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='office_phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
