# Generated by Django 2.2.12 on 2020-07-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0057_auto_20200702_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='application_identifier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
