# Generated by Django 2.2.12 on 2020-09-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0059_auto_20200715_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcharge',
            name='core_id_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
