# Generated by Django 2.2.12 on 2020-09-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0060_staffcharge_core_id_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='set_for_autologout',
            field=models.BooleanField(default=False),
        ),
    ]
