# Generated by Django 2.2.12 on 2020-10-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0061_auto_20200909_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='allow_autologout',
            field=models.BooleanField(default=False, help_text='Allow users to set an end time for the tool run.'),
        ),
    ]
