# Generated by Django 2.2.12 on 2020-11-03 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0062_tool_allow_autologout'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaaccessrecord',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areaaccessrecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
