# Generated by Django 2.2.12 on 2021-01-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0063_auto_20201103_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaaccessrecordproject',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
