# Generated by Django 2.2.12 on 2021-02-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0065_project_detailed_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='simba_cost_center',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
