# Generated by Django 2.2.12 on 2021-02-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0066_project_simba_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='po_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='account',
            field=models.ForeignKey(blank=True, help_text='All charges for this project will be billed to the selected account.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.Account'),
        ),
    ]
