# Generated by Django 2.2.12 on 2021-04-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0068_auto_20210225_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='end_scheduled_outage',
            field=models.BooleanField(default=False),
        ),
    ]
