# Generated by Django 2.2.12 on 2021-08-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0072_auto_20210817_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaaccessrecord',
            name='related_usage_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aar_related_usage_event', to='NEMO.UsageEvent'),
        ),
        migrations.AddField(
            model_name='staffcharge',
            name='related_usage_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sc_related_usage_event', to='NEMO.UsageEvent'),
        ),
    ]
