# Generated by Django 2.2.12 on 2021-09-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0073_auto_20210823_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablewithdraw',
            name='cost_per_sample_run',
            field=models.BooleanField(default=False),
        ),
    ]
