# Generated by Django 2.2.12 on 2021-11-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0075_project_bill_to_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageeventproject',
            name='cost_per_sample',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
