# Generated by Django 2.2.12 on 2021-11-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0077_auto_20211109_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='qualification_duration',
            field=models.PositiveIntegerField(blank=True, default=182, help_text="The tool may indicate the number of days without use a user will be considered qualified.  The default is 182 days (6 months).  Each night a script will run to check a user's last date of use for a tool against this time period.  If the date of last use is greater than the qualification_duration value the user will be set to probationary status.  This change can be reversed in LEO.", null=True),
        ),
    ]
