# Generated by Django 2.2.12 on 2022-03-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0080_userprofile_userprofilesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilesetting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilesetting',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
