# Generated by Django 2.2.12 on 2022-03-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0081_auto_20220329_1255'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userprofilesetting',
            constraint=models.UniqueConstraint(fields=('name',), name='unique name'),
        ),
    ]
