# Generated by Django 3.2.13 on 2022-05-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0082_auto_20220331_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
