# Generated by Django 3.2.15 on 2022-10-25 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0083_user_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='training_required',
            field=models.BooleanField(default=False, help_text='When selected, the user is blocked from all reservation and tool usage capabilities.'),
        ),
        migrations.CreateModel(
            name='ToolUseNotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='The HTML message sent to the user', null=True)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('tool', models.ForeignKey(help_text='The tool that this configuration option applies to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.tool')),
                ('usage_event', models.ForeignKey(help_text='The usage event which is running long', null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.usageevent')),
            ],
        ),
    ]
