# Generated by Django 3.2.13 on 2022-06-22 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0083_user_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='training_required',
            field=models.BooleanField(default=False, help_text='When selected, the user is blocked from all reservation and tool usage capabilities.'),
        ),
        migrations.CreateModel(
            name='TransactionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cost_per_sample', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sample_num', models.IntegerField(blank=True, null=True)),
                ('process_status', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_group_creator', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_group_customer', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_group_project', to='NEMO.project')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='transaction_groups',
            field=models.ManyToManyField(related_name='reservation_transaction_groups', to='NEMO.TransactionGroup'),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='transaction_groups',
            field=models.ManyToManyField(related_name='usage_event_transaction_groups', to='NEMO.TransactionGroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='transaction_groups',
            field=models.ManyToManyField(help_text='transaction groups the user may be working on', related_name='user_transaction_groups', to='NEMO.TransactionGroup'),
        ),
    ]
