# Generated by Django 3.2.15 on 2022-12-06 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0084_auto_20221025_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSchemeToolAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=255)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nsta_created_by', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.tool')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nsta_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
