# Generated by Django 3.2.13 on 2022-06-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0084_auto_20220622_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationproject',
            name='cost_per_sample',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservationproject',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationproject',
            name='sample_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
