# Generated by Django 3.2.13 on 2022-06-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0085_auto_20220623_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cost_per_sample_run',
            field=models.BooleanField(default=False),
        ),
    ]
