# Generated by Django 3.2.15 on 2023-01-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0085_notificationschemetoolaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffChargeNotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='The HTML message sent to the user', null=True)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('staff_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.staffcharge')),
            ],
        ),
    ]
