# Generated by Django 3.2.14 on 2022-07-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0086_reservation_cost_per_sample_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationproject',
            name='transaction_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.transactiongroup'),
        ),
        migrations.AddField(
            model_name='usageeventproject',
            name='transaction_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.transactiongroup'),
        ),
    ]
