# Generated by Django 3.2.15 on 2023-02-15 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0087_auto_20230214_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 15, 14, 9, 28, 963328), null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 15, 14, 9, 28, 963372), null=True),
        ),
    ]
