# Generated by Django 3.2.15 on 2023-03-29 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0088_auto_20230215_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='customer_nickname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 29, 13, 43, 16, 888658), null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 29, 13, 43, 16, 888734), null=True),
        ),
    ]
