# Generated by Django 3.2.15 on 2023-04-28 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0089_auto_20230329_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaaccessrecordproject',
            name='area_access_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.areaaccessrecord'),
        ),
        migrations.AlterField(
            model_name='areaaccessrecordproject',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='areaaccessrecordproject',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.project'),
        ),
        migrations.AlterField(
            model_name='reservationnotification',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.reservation'),
        ),
        migrations.AlterField(
            model_name='reservationnotification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservationproject',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservationproject',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.project'),
        ),
        migrations.AlterField(
            model_name='reservationproject',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.reservation'),
        ),
        migrations.AlterField(
            model_name='reservationproject',
            name='sample',
            field=models.ManyToManyField(blank=True, to='NEMO.Sample'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='staffcharge',
            name='related_override_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.staffcharge'),
        ),
        migrations.AlterField(
            model_name='staffchargeproject',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffchargeproject',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.project'),
        ),
        migrations.AlterField(
            model_name='staffchargeproject',
            name='staff_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.staffcharge'),
        ),
        migrations.AlterField(
            model_name='usageeventproject',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usageeventproject',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.project'),
        ),
        migrations.AlterField(
            model_name='usageeventproject',
            name='usage_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.usageevent'),
        ),
        migrations.CreateModel(
            name='UsageEventProjectSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('active_flag', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.sample')),
                ('usage_event_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.usageeventproject')),
            ],
        ),
        migrations.AddField(
            model_name='usageeventproject',
            name='sample_detail',
            field=models.ManyToManyField(blank=True, related_name='uep_sample_detail', through='NEMO.UsageEventProjectSample', to='NEMO.Sample'),
        ),
    ]
