# Generated by Django 3.2.15 on 2023-05-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0091_auto_20230502_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaaccessrecordproject',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='staffchargeproject',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='usageeventproject',
            name='sample',
        ),
    ]
