# Generated by Django 3.2.15 on 2023-07-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0092_auto_20230505_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watching',
            field=models.ManyToManyField(blank=True, help_text='Tools watched for notifications', related_name='tool_watchers', to='NEMO.Tool'),
        ),
    ]
