# Generated by Django 3.2.15 on 2023-11-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0094_auto_20231110_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='project2dcc',
            name='leo_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.project'),
        ),
    ]
