# Generated by Django 3.2.15 on 2023-12-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0095_project2dcc_leo_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project2dcc',
            name='project_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
