# Generated by Django 3.2.15 on 2024-03-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0096_alter_project2dcc_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcharge',
            name='credit_cost_collector_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
