# Generated by Django 3.2.15 on 2024-08-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0098_workorder_workordertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='work_order_type',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
