# Generated by Django 5.1.3 on 2025-01-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0100_workorder_created_by_workorder_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interlocktype',
            name='power_off_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interlocktype',
            name='power_on_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interlocktype',
            name='relay_prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interlocktype',
            name='relay_suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='interlocks',
            field=models.ManyToManyField(blank=True, related_name='interlocks', to='NEMO.interlock'),
        ),
    ]
