# Generated by Django 5.1.3 on 2025-02-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0102_consumableorder_consumableorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumableorder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumableorder',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
