# Generated by Django 5.1.3 on 2025-02-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0103_consumableorder_description_consumableorder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='consumables',
            field=models.ManyToManyField(blank=True, help_text='Select the consumables that are required for this tool. Consumables are used to track the amount of consumable used during a tool run.  This is not a required field.', related_name='tool_consumables', to='NEMO.consumable'),
        ),
    ]
