# Generated by Django 5.1.3 on 2025-05-19 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0105_consumable_supply_manager_consumableorder_cancelled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('external_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('industry_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEMO.consumable')),
            ],
            options={
                'ordering': ['consumable'],
            },
        ),
    ]
