# Generated by Django 5.1.3 on 2025-05-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0106_consumablerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumableorderitem',
            name='consumable_withdraw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_withdraw', to='NEMO.consumablewithdraw'),
        ),
    ]
