# Generated by Django 5.1.3 on 2025-06-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0107_consumableorderitem_consumable_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_shareable_calendar_link',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
