# Generated by Django 5.1.3 on 2025-09-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0109_requirement_arearequirement_toolrequirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='interlocks',
            field=models.ManyToManyField(blank=True, related_name='tools', to='NEMO.interlock'),
        ),
        migrations.AlterField(
            model_name='userrequirementprogress',
            name='status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='not_started', max_length=32, null=True),
        ),
    ]
