# Generated by Django 5.1.3 on 2025-09-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0110_alter_tool_interlocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequirementprogress',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrequirementprogress',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
