# Generated by Django 5.1.3 on 2025-10-03 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0111_alter_userrequirementprogress_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('core', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.core')),
                ('principle_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_type_principle_assignee', to=settings.AUTH_USER_MODEL)),
                ('requirements', models.ManyToManyField(blank=True, related_name='service_type_requirements', to='NEMO.requirement')),
                ('secondary_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_type_secondary_assignee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='service_types',
            field=models.ManyToManyField(blank=True, help_text='Select the service types that are applicable to this tool.', to='NEMO.servicetype'),
        ),
    ]
