# Generated by Django 5.1.3 on 2025-11-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0112_servicetype_tool_service_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='notification_interval',
            field=models.PositiveIntegerField(blank=True, default=7, null=True),
        ),
    ]
