# Generated by Django 5.1.3 on 2025-11-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0113_requirement_notification_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='expected_completion_time',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Expected time to complete this requirement in minutes.', null=True),
        ),
    ]
