# Generated by Django 5.1.3 on 2025-11-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0114_requirement_expected_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='login_requirement_flag',
            field=models.BooleanField(default=False, help_text='Checked if this requirement is used during login to see if this is a new user and the requirements are automatically added'),
        ),
    ]
