# Generated by Django 5.1.3 on 2025-12-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0115_requirement_login_requirement_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='automated_update',
            field=models.BooleanField(default=False, help_text='Checked if this requirement is automatically updated by an external system'),
        ),
    ]
