# Generated by Django 5.1.3 on 2025-12-16 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0116_requirement_automated_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('training_request', models.BooleanField(blank=True, default=False)),
                ('case_number', models.CharField(blank=True, max_length=255, null=True)),
                ('core', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.core')),
                ('pi_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_for_service_request', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.project')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NEMO.servicetype')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NEMO.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userrequirementprogress',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.userservicerequest'),
        ),
        migrations.AddConstraint(
            model_name='userservicerequest',
            constraint=models.CheckConstraint(condition=models.Q(('tool__isnull', True), ('service_type__isnull', True), _negated=True), name='either_tool_or_service'),
        ),
    ]
