# Generated by Django 5.1.3 on 2026-01-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0117_userservicerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='retrain_interval_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
