# Generated by Django 5.1.3 on 2026-01-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0118_requirement_prerequisites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicerequest',
            name='owner',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
