# Generated by Django 5.1.3 on 2026-01-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0119_userservicerequest_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='resource_link_name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='resource_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
