# Generated by Django 5.1.3 on 2026-02-03 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0120_requirement_resource_link_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicerequest',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
