# Generated by Django 5.1.3 on 2026-02-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0121_userservicerequest_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicerequest',
            name='training_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
