# Generated by Django 5.1.3 on 2026-02-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0122_userservicerequest_training_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='auto_include',
            field=models.BooleanField(default=False),
        ),
    ]
