# Generated by Django 5.1.3 on 2026-03-05 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0123_servicetype_auto_include'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicerequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userservicerequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usr_cancelled_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
