# Generated by Django 5.1.3 on 2026-04-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0124_userservicerequest_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='logical_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
