# Generated by Django 5.2.13 on 2026-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0125_requirement_logical_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservicerequest',
            name='status',
            field=models.CharField(default='OPEN', max_length=32),
        ),
    ]
