# Generated by Django 5.2.13 on 2026-06-18 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0126_alter_userservicerequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTypeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='The question to display to the user', max_length=5000)),
                ('field_name', models.CharField(help_text='Internal field name (snake_case, no spaces)', max_length=1000)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('select', 'Dropdown'), ('multiselect', 'Multiple Selection'), ('checkbox', 'Checkbox'), ('radio', 'Radio Button'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('time', 'Time')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_required', models.BooleanField(default=False)),
                ('help_text', models.TextField(blank=True, help_text='Additional help text shown below the field')),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text for input fields', max_length=255)),
                ('choices_json', models.JSONField(blank=True, help_text='JSON array of choices for select fields', null=True)),
                ('trigger_value', models.CharField(blank=True, help_text='Show this question when parent has this value', max_length=255)),
                ('validation_rules', models.JSONField(blank=True, help_text='Validation rules as JSON', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_questions', to='NEMO.servicetypequestion')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='NEMO.servicetype')),
            ],
            options={
                'ordering': ['service_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserServiceRequestAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(help_text='Answer stored as text (can be JSON for complex types)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NEMO.servicetypequestion')),
                ('user_service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_answers', to='NEMO.userservicerequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='servicetypequestion',
            index=models.Index(fields=['service_type', 'is_active', 'order'], name='NEMO_servic_service_438fb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicetypequestion',
            unique_together={('service_type', 'field_name')},
        ),
        migrations.AddIndex(
            model_name='userservicerequestanswer',
            index=models.Index(fields=['user_service_request', 'question'], name='NEMO_userse_user_se_4b16e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userservicerequestanswer',
            unique_together={('user_service_request', 'question')},
        ),
    ]
