# Generated by Django 5.2.13 on 2026-06-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0127_servicetypequestion_userservicerequestanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='autocompleted',
            field=models.BooleanField(default=False, help_text='Checked if this requirement is added with a status of completed in UserRequirementProgress'),
        ),
    ]
