# Generated by Django 5.2.13 on 2026-06-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0128_requirement_autocompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='auto_include',
            field=models.BooleanField(default=False, help_text="Checked when a requirement doesn't require some sort of approval before assignement"),
        ),
    ]
