# Generated by Django 5.2.13 on 2026-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0129_requirement_auto_include'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='logical_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
