# Generated by Django 5.2.13 on 2026-10-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0130_servicetype_logical_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='preferred email address'),
        ),
    ]
