from setuptools import setup, find_packages

setup(
	name='LEO',
	version='2.0.0',
	python_requires='>=3.10',
	packages=find_packages(exclude=['NEMO.tests']),
	include_package_data=True,
	url='https://github.com/usnistgov/NEMO',
	license='Public domain',
	author='Center for Nanoscale Science and Technology',
	author_email='CNSTapplications@nist.gov',
	description='NEMO is a laboratory logistics web application. Use it to schedule reservations, control tool access, track maintenance issues, and more.',
	long_description='Find out more about NEMO on the GitHub project page https://github.com/usnistgov/NEMO',
	classifiers=[
		'Development Status :: 5 - Production/Stable',
		'Environment :: Web Environment',
		'Framework :: Django',
		'Intended Audience :: Science/Research',
		'Intended Audience :: System Administrators',
		'License :: Public Domain',
		'Natural Language :: English',
		'Operating System :: OS Independent',
		'Programming Language :: Python :: 3.10',
		'Programming Language :: Python :: 3.11',
		'Programming Language :: Python :: 3.12',
	],
	install_requires=[
		'cryptography>=3.1.0',
		'Django==5.2.13',
		'django-filter>=2.2.0',
		'djangorestframework>=3.8.2',
		'ldap3>=2.7.0',
		'python-dateutil>=2.8.1',
		'requests>=2.23.0',
		'Pillow>=7.1.1',
		'pyjwt>=1.7.1',
		'icalendar>=6.3.0',
		'setuptools>=65.0.0',
	],
	entry_points={
		'console_scripts': ['nemo=NEMO.provisioning:entry_point'],
	},
)